"""add final score to interviews

Revision ID: 53583e1fff67
Revises: 69ba5c229389
Create Date: 2026-08-14 22:16:12.710030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53583e1fff67'
down_revision: Union[str, Sequence[str], None] = '69ba5c229389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_answers')
    op.add_column('interviews', sa.Column('final_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'final_score')
    op.create_table('interview_answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('interview_question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ai_feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['interview_question_id'], ['interview_questions.id'], name=op.f('interview_answers_interview_question_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_answers_pkey'))
    )
    # ### end Alembic commands ###
