"""add final feedback to interviews

Revision ID: 69ba5c229389
Revises: fad46218892a
Create Date: 2026-08-14 21:50:41.674562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69ba5c229389'
down_revision: Union[str, Sequence[str], None] = 'fad46218892a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('final_feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'final_feedback')
    op.create_table('interview_answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('interview_question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ai_feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['interview_question_id'], ['interview_questions.id'], name=op.f('interview_answers_interview_question_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_answers_pkey'))
    )
    # ### end Alembic commands ###
